development:
  adapter: postgresql
  encoding: unicode
  database: moto_development
  pool: 5
  username: postgres
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: moto_production
  pool: 5
  username: deploy
  password: deploy 