development:
  adapter: postgresql
  encoding: unicode
  database: municipalities_development
  pool: 5
  username: postgres
  password: 

production:
  adapter: postgresql
  encoding: unicode
  database: municipalities_production
  pool: 5
  username: deploy
  password: deploy