development:
  adapter: postgresql
  encoding: unicode
  database: passes_development
  pool: 5
  username: postgres
  password: 

development:
  adapter: postgresql
  encoding: unicode
  database: passes_production
  pool: 5
  username: deploy
  password: deploy